### ISSUE TITLE
 Nuclide-Quick-Open Error After Update to 0.0.25

### ISSUE THREAD

**Issue by ChristianGrech** [facebook/nuclide#156]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Microsoft Windows 8.1
**Thrown From**: [nuclide-quick-open](https://github.com/facebooknuclideapm/nuclide-quick-open) package, v0.0.25

### Stack Trace

Uncaught Error: Cannot find module 'underscore-plus'

```
At module.js:330

Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\behavior.js:7:13)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\behavior.js:120:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\helpers.js:5:14)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\helpers.js:55:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\emissary.js:4:13)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\emissary.js:14:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\lib\grim.js:4:13)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\lib\grim.js:105:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\lib\disposable.js:4:10)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\lib\disposable.js:39:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\lib\emitter.js:4:16)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\lib\emitter.js:91:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\lib\event-kit.js:2:21)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\lib\event-kit.js:8:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\lib\NuclideRemoteEventbus.js:19:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-remote-connection\lib\RemoteConnection.js:32:29)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-remote-connection\lib\main.js:10:24)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\lib\service-manager.js:23:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\lib\main.js:11:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at initSearch (C:\Users\Christian\.atom\packages\nuclide-quick-open\lib\main.js:273:19)
  at Emitter.module.exports.Emitter.emit (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Project.module.exports.Project.addPath (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\project.js:274:29)
  at EventEmitter.<anonymous> (C:\Users\Christian\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-event-handler.js:37:32)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "material"
    ],
    "projectHome": "C:\\wamp\\www\\",
    "disabledPackages": [
      "remote-edit",
      "nuclide-language-hack",
      "hyperclick",
      "tree-view",
      "nuclide-flow"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.18.0
autocomplete-php, v0.3.6
linter, v1.3.0
linter-php, v1.0.2
material, v2.1.4
nuclide-arcanist, v0.0.25
nuclide-code-format, v0.0.25
nuclide-diagnostics-store, v0.0.25
nuclide-diagnostics-ui, v0.0.25
nuclide-diff-view, v0.0.25
nuclide-file-tree, v0.0.25
nuclide-file-watcher, v0.0.25
nuclide-hack, v0.0.25
nuclide-hg-repository, v0.0.25
nuclide-installer, v0.0.25
nuclide-ocaml, v0.0.25
nuclide-quick-open, v0.0.25
nuclide-remote-projects, v0.0.25
nuclide-type-hint, v0.0.25
php-debug, v0.1.2
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by bolinfest** [comment]
Are you sure that all of the packages installed via `nuclide-installer` have finished installing?

**Comment by ChristianGrech** [comment]
Yes everything installed from nuclide-installer. The issue happened after I updated it.

**Comment by bolinfest** [comment]
What is in `C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary`? Is there a `node_modules` with an `underscore_plus` directory?

**Comment by ChristianGrech** [comment]
It seems to be an emitter package. Here are the first few lines of the package.json

```
"name": "emissary",
  "version": "1.3.3",
  "description": "Utility mixins for subscribing to and emitting events.",
  "main": "lib/emissary.js",
  "scripts": {
    "test": "grunt test",
    "prepublish": "grunt clean lint coffee"
  },
  "repository": {
    "type": "git",
    "url": "http://github.com/atom/emissary.git"
  }

**Comment by arsenx** [comment]
I am also getting an error related to the `nuclide-quick-open` package

**System:** OSX 10.10.4
**Atom:** 1.0.3
**Nuclide:** 0.0.26

<img width="1166" alt="screen shot 2015-08-03 at 10 36 53 pm" src="https://cloud.githubusercontent.com/assets/5718879/9052279/a51fac62-3a33-11e5-8f1d-54190b314997.png">

I think the error message code might help in resolving the issue.
It just searches forever with no results.

Also this error may be cascading and causing the new issue I will file in a few minutes

**Comment by bolinfest** [comment]
@ChristianGrech I believe the error you are seeing in the quick open dialog is due to the "untitled" editor pane you have open. Under the hood, we are probably calling `atom.workspace.getActiveTextEditor().getPath()`, which is failing.

We need to add a null check, but for now, maybe closing the pane will fix your immediate issue?

**Comment by bolinfest** [comment]
@ChristianGrech Yes, but does `C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary\node_modules` exist? Or is there ancestor folder with a `node_modules` that has a copy of `underscore` in it?

I'm curious if something did not get installed properly. You could try doing the following to fix it:

```
cd C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary\
npm install
```

**Comment by arsenx** [comment]
You're right the untitled file was the one causing the message but is not the real problem. The problem is that it does not find any results to any search.

<img width="1440" alt="screen shot 2015-08-03 at 11 32 56 pm" src="https://cloud.githubusercontent.com/assets/5718879/9052681/53e52d18-3a38-11e5-8b8d-ff827f5426a9.png">

**Comment by bolinfest** [comment]
@arsenx Did you follow all of the instructions on http://nuclide.io/docs/remote/ for setting up your remote server?

**Comment by arsenx** [comment]
Yes I did at 100% @bolinfest but as you'll be able to see in the picture above the problem is occurring on local projects too. Let me know if you need me to do any testing.

**Comment by bolinfest** [comment]
Ah, @arsenx, I think you're going to have a problem with local projects because Watchman is not available for Windows...yet: https://github.com/facebook/watchman/issues/19.

Flow isn't available for Windows, and our Mercurial support also depends on Watchman. Currently, the biggest value add we provide for Windows users is the ability to connect to a remote *nix machine and edit files there where our other tools that depend on *nix are installed.

**Comment by arsenx** [comment]
I'm on OS X 10.10.4 @bolinfest it's @ChristianGrech who's on windows 8.1, I don't have watchman installed on my mac though... is it necessary for quick open to work?

**Comment by bolinfest** [comment]
@arsenx Yes, I believe it is. I thought we updated the docs to make that clear. I can't find evidence that we did :(

Admittedly, it's a bit of work to even trace through the dependencies to deduce this:

* `nuclide-quick-open` depends on `nuclide-client`
* `NuclideClient` provides a `doSearchQuery` method that maps to a `/search/query` path.
* In `nuclide-server`, there is a `services-config.json` file that has an entry for our legacy service framework for `lib/services/NuclideSearchService.js`.
* In `lib/services/NuclideSearchService.js`, you can see where the mapping for `/search/query` occurs.
* `NuclideSearchService.js` depends on `nuclide-path-search`.
* `nuclide-path-search` depends on `nuclide-watchman-helpers`.
* The final piece of the puzzle is https://github.com/facebook/nuclide/blob/b16f67a/pkg/nuclide/path-search/lib/PathSetUpdater.js#L15-L17

/cc @jssln Do you remember us updating this somewhere? Maybe we only did this for the Mercurial package?

**Comment by arsenx** [comment]
Wow that is a huge chain of dependants, it definitely deserves to be mentioned in the docs hahahahha

So I tried installing watchman from brew and also nuclide-client using npm on my mac (client side) and still get no search results seems really odd. Still no search results both **locally** and **remotely**.
I wonder if I am the only one experiencing this issue or if it happens to others as well.

**Comment by bolinfest** [comment]
Is there anything of interest in `/tmp/nuclide-<YOUR USERNAME>-logs/`?

**Comment by arsenx** [comment]
So if you have read all the way down this issue and gotten to this post then congrats here is the magical touch that will make your `nuclide-quick-open` work

Sorry windows guys @bolinfest says you have to wait for watchman for windows
If you're on a mac make sure you install the **Latest** version of watchman by essentially using the
```
brew install --HEAD watchman
```
Otherwise you will not be able to use the `nuclide-quick-open` feature

I will refer to this issue #87 since they are related in some way
Good luck everyone and thanks @bolinfest for the great help!

**Comment by ChristianGrech** [comment]
@bolinfest sorry for the delay. Under `C:\Users\Christian\.atom\packages\nuclide-quick-open\node_modules\nuclide-client\node_modules\nuclide-server\node_modules\event-kit\node_modules\grim\node_modules\emissary` there is a folder `node_modules` under which underscore-plus is installed. See tree image below.
![image](https://cloud.githubusercontent.com/assets/4950218/9087777/02392572-3b8d-11e5-9b97-20e332fe7723.png)

**Comment by bolinfest** [comment]
Here is the fix for quick open crashing on the "undefined" editor tab: https://github.com/facebook/nuclide/commit/eb0e3aeb7fbe969d387f7c76d379dfc0d70b358e

**Comment by bolinfest** [comment]
@arsenx Awesome: glad you got that sorted out! We'll have to update our `brew` recipe so people fall into the pit of success.

**Comment by bolinfest** [comment]
@ChristianGrech Hmm, that seems odd then. Though we had at least one anecdotal report of problems on Windows when paths are too long? Specifically from https://github.com/facebook/nuclide/issues/23:

> Firstly I had issue with long path - longer that allowed on Windows OS.
> This issue is fixed in NPM somehow but in your python script it's not.
> I temporary solved this by moving it closer to core path.

Maybe that is the case here?

**Comment by ssorallen** [comment]
Can you try the latest release, v0.111.0 of 'nuclide'? The nuclide-quick-open package is no longer supported.

http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
