### ISSUE TITLE
settings not showing up in ATOM

### ISSUE THREAD

**Issue by mayurbaldha** [facebook/nuclide#1156]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
Atom 1.17.0 x64 with nuclide

### Expected Behavior
Nuclide settings button should show up
### Actual Behavior
Nuclide Settingsbutton not showing up.

### Versions
* Atom: 1.17.0 x64
* Nuclide: 0.228.0
* Client OS: Windows
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by arunpalani-vbi** [comment]
After updating nuclide to 0.228.0, Same issue observed in my system.

OS: Windows 8.1 x64 Pro
Atom : 1.18.0-beta0 x64
Nuclide: 0.228.0

**Comment by mayurbaldha** [comment]
Downgrade ATOM Version to Atom: 1.17.0 x64.. & Nuclide will work to see settings

**Comment by arunpalani-vbi** [comment]
@mayurbaldha  I think this is not a proper solution

**Comment by ebluestein** [comment]
Hey all, we are currently investigating this issue. In the meantime, can you get to Nuclide settings by clicking the gear on the toolbar near the lower left corner of the screen?

**Comment by arunpalani-vbi** [comment]
Hey @ebluestein , I done a rebuild for nuclide in atom, Now its works..

**Comment by friscoMad** [comment]
Happening again with Atom 1.18 x64 and Nuclide 0.232.0

```
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
ctags@0.2.3 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\ctags\build\ctags-v0.2.3-electron-v1.3-win32-x64\ctags.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
fuzzy-native@0.6.5 – Cannot find module 'C:\Users\Frisco\.atom\packages\nuclide\node_modules\nuclide-prebuilt-libs\fuzzy-native\build\fuzzy-native-v0.6.5-electron-v1.3-win32-x64\fuzzy-native.node'
```
