### ISSUE TITLE
Failed to activate the nuclide-debugger-atom package

### ISSUE THREAD

**Issue by urzds** [facebook/nuclide#246]
[Enter steps to reproduce below:]

1. Open new Atom window
2. See error message

**Atom Version**: 1.2.0
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-debugger-atom](https://github.com/facebooknuclideapm/nuclide-debugger-atom) package, v0.0.32

### Stack Trace

Failed to activate the nuclide-debugger-atom package

```
At deprecationSite.getFileName is not a function

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/usr/share/atom/resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at Object.defineProperty.get [as TextEditor] (/usr/share/atom/resources/app.asar/exports/atom.js:38:14)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-debugger-atom/lib/BreakpointManager.js:17:26)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-debugger-atom/lib/DebuggerModel.js:18:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.32
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.2
latexer, v0.2.7
linter, v1.10.0
linter-csslint, v1.1.0
linter-gcc, v0.3.9
linter-htmlhint, v0.2.1
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.3
linter-rust, v0.2.10
linter-tidy, v1.0.1
minimap, v4.16.0
nuclide-arcanist, v0.0.32
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-test-runner, v0.0.32
nuclide-toolbar, v0.0.32
nuclide-type-hint, v0.0.32
pdf-view, v0.34.0

# Dev
No dev packages
```

**Comment by scv119** [comment]
Thanks for reporting, all these seem to be compatibility issue with Atom 1.2.0, will have a look soon.

**Comment by urzds** [comment]
See-Also: atom/atom#9350

**Comment by mormy** [comment]
Same on OSX ...

**Comment by bgnlordhelmut** [comment]
Seems to be present on the latest Atom beta as well, 1.3.0_beta0

**Comment by pietrovismara** [comment]
Same here, i have to remove all nuclide packages to make atom usable :cry:

**Comment by steblar** [comment]
Temporary solution to make Atom not download new version.
On osx and Linux edit, as root, file: /etc/hosts and add the line below

#atom fix
127.0.0.1      atom.io

Because to download new version Atom auto check https://atom.io/api/updates?version

Last Atom version compatible with nuclide package: 1.1.0 that can be downloaded here: https://github.com/atom/atom/releases?after=v1.2.0-beta0

**Comment by mr16839072** [comment]
Just downloaded Atom + Nuclide today, nothing worked :cry:

**Comment by kgdev** [comment]
When can it be fixed?

**Comment by tonyxiao** [comment]
Isn't this a "Unbreak now" type of issue because it renders the entire nuclide project unusable? I tried @steblar 's workaround also but atom still seem to update itself. Did anyone else find a different workaround?

**Comment by mr16839072** [comment]
Yeah I thought something like this would be top priority

**Comment by bgnlordhelmut** [comment]
I was able to work around the issue:

I removed literally as much as I could find related to Atom on my system, essentially uninstalling it:

~/.atom
/usr/local/bin/atom
/usr/local/bin/apm
/Applications/Atom.app
~/Library/Preferences/com.github.atom.plist
~/Library/Application Support/com.github.atom.ShipIt
~/Library/Application Support/Atom
~/Library/Saved Application State/com.github.atom.savedState
~/Library/Caches/com.github.atom
~/Library/Caches/Atom

I then downloaded latest (v.1.2.3), installed, and it's running fine again with no CPU issues (see here: https://github.com/atom/atom/issues/3426). I then installed Nuclide and things seem to be running fine again.

**Comment by mr16839072** [comment]
That's strange @bgnlordhelmut because I downloaded everything for the first time a few days ago (inc. 1.2.3) and it didn't work for me... Strange.  Maybe i'll try and re-install and see what happens

**Comment by maximilianmessing** [comment]
I have the same issue on OSX with a fresh install

**Comment by mr16839072** [comment]
[errors1](http://imgur.com/GaqRVp3) 
[errors2](http://imgur.com/WFc0bqK)

**Comment by scv119** [comment]
This bug is fixed in https://github.com/facebook/nuclide/commit/c725896010916f5db7662929a4bd6598c796c120 and I am working on an Atom fix in https://github.com/atom/atom/issues/964. 

But we need a release to fix this problem cc @jamesgpearce

**Comment by nmote** [comment]
@scv119 I don't think that's the right Atom PR

**Comment by scv119** [comment]
Oops, updated. Thanks!

**Comment by sequethin** [comment]
looks like I picked the wrong day to try Atom + Nuclide. Glad to see a fix is in the works!

**Comment by tonyxiao** [comment]
Got it, does this mean I can install the latest nuclide-installer from apm and everything should just work now? Or is it going to take another release for this fix to make it in?

**Comment by nmote** [comment]
It's going to take another release. See my comments on #251 for an explanation about the long delay since the last release. We were hoping to hold off until we get the huge install size and bad performance fixed, but this issue might warrant a release anyway.

I know this isn't a great answer, but you can always build from source. The way our setup script works alleviates some of the performance and size problems with the released version. And, you'll pick up this fix immediately.

**Comment by tonyxiao** [comment]
@nmote Thanks for the workaround suggestion. I'll give it a try!

**Comment by davidlygagnon** [comment]
I'm also having this problem today.

**Comment by evilantnie** [comment]
+1 here, just adding my vote for a fix on this

**Comment by mr16839072** [comment]
@nmote I build from master and indeed the problem goes away.  One thing I did notice however, was that there are significantly less packages in the .atom/packages dir using the setup script that when using the installer through apm, is this expected behaviour?

**Comment by zuhair-naqvi** [comment]
Building from source does work.. Any idea when the fixes will be released?

**Comment by nmote** [comment]
Don't quote me on this, but there has been talk of doing one today. I'm not sure if it will happen or not. If not, it's likely to be sometime next week.

**Comment by zuhair-naqvi** [comment]
Yay! I'm so gonna quote you if there isn't one today haha

**Comment by appsforartists** [comment]
@nmote I don't know if this helps motivate a release, but I was also unable to use `nuclide-server`; I kept getting `Cannot read property localImplementation of undefined` errors in both the red Atom error dialog on my laptop and in `/tmp/nuclide-appsforartists-logs` on the server.

I tried installing the package from source and adding `nuclide/pkg/nuclide/server` to my path; everything appears to be working now.

**Comment by eeeee** [comment]
I'm getting a similar issue on Atom 1.19.0-beta4 (on Windows 10). I can "Add Remote Project Folder" fine, but when I click on any remote file name I get a "Failed to open nuclide://<filename here>: deprecationSite.getFileName is not a function".
Nuclide worked fine in Atom 1.18.0, but I have to use 1.19.0 because the fonts in 1.18.0 are too blurry.

**Comment by nicodmf** [comment]
Idem on linux

**Comment by imperio59** [comment]
Same on Atom 1.19.0/Nuclide on mac OSX and a remote project folder.

**Comment by tjaklitsch** [comment]
Same on Atom 1.19.2.  There a timeline on a fix for this?

**Comment by winterlightning** [comment]
Same error on 1.19.0 on mac OSX and remote project
